/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multimoduleprojecttake1.app.helloworld

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
